version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
 
  build:
    commands:
      - python manage.py collectstatic --noinput
      - python manage.py migrate
 
 
artifacts:
  files:
    - Procfile
    - requirements.txt
    - runtime.txt
    - .ebextensions/**  # Include EB config if present